#!/usr/bin/env python3
# vi:fileencoding=utf-8
from __future__ import absolute_import
from __future__ import division
from __future__ import unicode_literals
from __future__ import print_function


if __name__ == '__main__':
    from gui import Application
    app = Application()
    app.top.mainloop()
